--DROP TABLE PT_TRAN_MAPPING_QLB;
CREATE TABLE PT_TRAN_MAPPING_QLB (
FORMAT VARCHAR2(10 CHAR) NULL ,
FORMAT_NAME VARCHAR2(60 CHAR) NULL ,
MSG_CODE VARCHAR2(20 CHAR) NULL ,
MSG_CODE_NAME VARCHAR2(60 CHAR) NULL ,
BUSI_TYPE VARCHAR2(6 CHAR) NULL ,
BUSI_TYPE_NAME VARCHAR2(60 CHAR) NULL ,
TRAN_CATEGORY VARCHAR2(5 CHAR) NULL ,
BUSI_CODE VARCHAR2(4 CHAR) NULL ,
TRAN_CATEGORY_NAME VARCHAR2(60 CHAR) NULL ,
SYS_CODE VARCHAR2(1 CHAR) NULL 
);

COMMIT;
